export const previewStyles = `
:host{display:block;width:100%;max-width:var(--simple-post-preview-max-width,390px);color-scheme:dark;contain:content;font-family:var(--simple-post-preview-font-family,Arial,Helvetica,sans-serif);-webkit-font-smoothing:antialiased}
*{box-sizing:border-box}p,h2{margin:0}img,video{max-width:100%}.sp-root{width:100%;overflow:hidden;background:#0a0a0a;color:#f5f5f5}
.sp-avatar{display:grid;place-items:center;flex:0 0 auto;width:40px;height:40px;overflow:hidden;border:1px solid rgba(255,255,255,.15);border-radius:50%;background:#525252;color:#fff;font-size:12px;font-weight:700}.sp-avatar img{width:100%;height:100%;object-fit:cover}.sp-avatar--32{width:32px;height:32px}.sp-avatar--36{width:36px;height:36px}.sp-avatar--48{width:48px;height:48px}
.sp-row{display:flex;align-items:center}.sp-grow{min-width:0;flex:1}.sp-truncate{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.sp-copy{white-space:pre-wrap;overflow-wrap:anywhere}.sp-muted{color:#a3a3a3}
.sp-media,.sp-media--natural,.sp-pin-media{position:relative}.sp-media{min-width:0;min-height:0;overflow:hidden;background:#171717}.sp-media img,.sp-media video{display:block;width:100%;height:100%;object-fit:cover}.sp-media--natural img,.sp-media--natural video{height:auto;max-height:720px;object-fit:contain;background:#000}.sp-play{position:absolute;inset:0;display:grid;place-items:center;background:rgba(0,0,0,.1)}.sp-play span{display:grid;place-items:center;width:48px;height:48px;border-radius:50%;background:rgba(0,0,0,.6)}.sp-play svg{width:21px;height:21px;fill:#fff}
.sp-empty{display:flex;align-items:center;justify-content:center;flex-direction:column;gap:8px;width:100%;height:100%;background:linear-gradient(135deg,#171717,#262626);color:#a3a3a3;font-size:12px;font-weight:600}.sp-empty svg{width:36px;height:36px;fill:none;stroke:currentColor;stroke-width:1.5}
.sp-x{background:#000;color:#e7e9ea}.sp-x-main{padding:32px}.sp-x-head{align-items:flex-start;gap:12px}.sp-x-name{padding-top:2px;font-size:15px;font-weight:700;line-height:20px}.sp-x-handle,.sp-x-time{font-size:15px;line-height:20px;color:#71767b}.sp-x-copy{margin-top:24px;font-size:17px;line-height:22px}.sp-x-media{margin-top:20px;border:1px solid #2f3336;border-radius:18px}.sp-x-time{margin-top:20px}.sp-x-thread{padding:16px 32px;border-top:1px solid #2f3336}.sp-x-thread .sp-row{align-items:flex-start;gap:12px}.sp-x-thread-copy{margin-top:4px;font-size:15px;line-height:20px}.sp-inline-meta{font-size:14px;line-height:20px}.sp-inline-meta b{margin-right:5px}
.sp-instagram{background:#000;color:#fafafa}.sp-instagram-head{gap:8px;padding:12px;font-size:12px;font-weight:600}.sp-instagram-blank{aspect-ratio:1}.sp-counter{position:absolute;right:12px;top:12px;padding:4px 8px;border-radius:999px;background:rgba(0,0,0,.7);color:#fff;font-size:10px;font-weight:600}.sp-instagram-copy{padding:12px 12px 16px;font-size:12px;line-height:16px}.sp-instagram-copy b{margin-right:5px}
.sp-facebook,.sp-linkedin{padding:12px 0;background:#1c1e21;color:#fafafa}.sp-facebook-head,.sp-linkedin-head{gap:10px;padding:0 12px}.sp-facebook-name,.sp-linkedin-name{font-size:13px;font-weight:600}.sp-facebook-meta,.sp-linkedin-meta{font-size:11px;color:#a3a3a3}.sp-facebook-copy,.sp-linkedin-copy{padding:8px 12px 12px;font-size:14px;line-height:18px}.sp-linkedin{background:#111827}.sp-linkedin-head{align-items:flex-start}.sp-linkedin-copy{font-size:13px}.sp-follow{align-self:flex-start;color:#71b7fb;font-size:11px;font-weight:600}
.sp-tiktok{position:relative;aspect-ratio:9/16;background:#000;color:#fff}.sp-tiktok>.sp-tiktok-media{position:absolute;inset:0}.sp-tiktok-media>.sp-media{height:100%}.sp-tiktok .sp-gallery-track{height:100%}.sp-tiktok .sp-gallery-slide{height:100%;aspect-ratio:auto}.sp-tiktok-shade,.sp-tiktok-avatar,.sp-tiktok-copy{pointer-events:none}.sp-tiktok-fallback{position:absolute;inset:0;background:linear-gradient(135deg,#06b6d4,#0a0a0a 52%,#ec4899)}.sp-tiktok-shade{position:absolute;inset:0;background:linear-gradient(to bottom,rgba(0,0,0,.3),transparent 42%,rgba(0,0,0,.72))}.sp-tiktok-avatar{position:absolute;left:12px;top:12px;border:2px solid #fff}.sp-tiktok-copy{position:absolute;left:12px;right:12px;bottom:20px;text-shadow:0 1px 3px #000}.sp-tiktok-copy p{font-size:12px;line-height:16px}.sp-tiktok-copy .sp-handle{font-size:14px;font-weight:600}.sp-tiktok-copy .sp-caption{display:-webkit-box;margin-top:4px;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:3}.sp-sound{display:flex;align-items:center;gap:7px;margin-top:8px;font-weight:600}.sp-sound svg{width:14px;height:14px;fill:none;stroke:currentColor;stroke-width:1.8}
.sp-youtube{background:#0f0f0f;color:#fafafa}.sp-youtube-empty{aspect-ratio:16/9}.sp-youtube-info{padding:12px 12px 16px}.sp-youtube-title{display:-webkit-box;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:2;font-size:15px;line-height:20px}.sp-youtube-meta{margin-top:4px;font-size:11px;color:#a3a3a3}.sp-youtube-channel{gap:8px;margin-top:12px}.sp-youtube-description{margin-top:12px;padding:12px;border-radius:12px;background:#171717;font-size:12px;line-height:16px;color:#e5e5e5}
.sp-telegram{padding:12px;background-color:#0e1621;background-image:radial-gradient(rgba(114,151,179,.16) 1px,transparent 1px);background-size:18px 18px;color:#f5f5f5}.sp-bubble{max-width:310px;margin-left:auto;overflow:hidden;border-radius:12px 12px 3px 12px;background:#243447;box-shadow:0 1px 2px rgba(0,0,0,.3)}.sp-bubble+.sp-bubble{margin-top:8px}.sp-bubble-copy{padding:8px 10px 6px;font-size:13px;line-height:17px}.sp-bubble-time{margin-top:4px;text-align:right;font-size:9px;color:#a3a3a3}
.sp-bluesky{background:#161e27;color:#fafafa}.sp-bluesky-post{padding:16px}.sp-bluesky-post+.sp-bluesky-post{border-top:1px solid #2e3a46}.sp-bluesky-head{gap:10px}.sp-bluesky-name{font-size:14px;font-weight:700;line-height:20px}.sp-bluesky-handle,.sp-bluesky-time{font-size:13px;line-height:17px;color:#aebbc9}.sp-bluesky-copy{margin-top:12px;font-size:16px;line-height:21px}.sp-bluesky-media{margin-top:12px;border:1px solid #2e3a46;border-radius:8px}.sp-bluesky-time{margin-top:12px}
.sp-threads{padding:16px;background:#000;color:#fafafa}.sp-thread-item{position:relative}.sp-thread-item+.sp-thread-item{padding-top:20px}.sp-thread-row{align-items:flex-start;gap:12px}.sp-thread-avatar{position:relative}.sp-thread-line{position:absolute;top:44px;bottom:-20px;left:50%;width:1px;background:#404040}.sp-thread-meta{font-size:13px}.sp-thread-age{float:right;color:#a3a3a3}.sp-thread-copy{margin-top:4px;font-size:14px;line-height:19px}.sp-thread-media{margin-top:8px;border:1px solid #262626;border-radius:16px}
.sp-pinterest{padding:12px;background:#111;color:#fafafa}.sp-pin-media{overflow:hidden;border-radius:24px;background:#171717}.sp-pin-empty{height:384px}.sp-pin-info{padding:12px 4px 0}.sp-pin-title{display:-webkit-box;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:2;font-size:18px;line-height:20px}.sp-pin-description{display:-webkit-box;margin-top:5px;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:3;white-space:pre-wrap;font-size:12px;line-height:16px;color:#d4d4d4}.sp-pin-account{gap:8px;margin-top:12px;font-size:12px;font-weight:600}
.sp-forem{background:#0f0f0f;color:#fafafa}.sp-forem-cover{height:224px}.sp-forem-info{padding:16px}.sp-forem-head{gap:8px;font-size:12px}.sp-forem-meta{font-size:10px;color:#a3a3a3}.sp-forem-title{display:-webkit-box;margin-top:16px;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:3;font-size:22px;line-height:28px}.sp-tags{display:flex;flex-wrap:wrap;gap:8px;margin-top:8px;font-size:12px}.sp-forem-copy{display:-webkit-box;margin-top:12px;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:5;white-space:pre-wrap;font-size:14px;line-height:20px;color:#d4d4d4}
.sp-unsupported{display:flex;min-height:256px;align-items:center;justify-content:center;padding:32px;background:#0a0a0a;text-align:center;color:#a3a3a3;font-size:13px}

.sp-viewport{width:100%;min-height:0}.sp-viewport--scroll{overflow-y:auto;overflow-x:hidden;overscroll-behavior-y:contain}.sp-viewport--expand{overflow:visible}
/* Gallery controls are overlays; each platform owns its feed presentation. */
.sp-sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
.sp-gallery{position:relative;min-width:0;overflow:hidden}.sp-gallery-stage{position:relative}.sp-gallery-track{position:relative;display:flex;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;direction:ltr;cursor:grab}.sp-gallery-track::-webkit-scrollbar{display:none}.sp-gallery-track.sp-dragging{scroll-snap-type:none;cursor:grabbing;user-select:none}.sp-gallery-slide{position:relative;flex:0 0 100%;min-width:0;aspect-ratio:var(--sp-media-ratio,1);scroll-snap-align:start;scroll-snap-stop:always;overflow:hidden}.sp-gallery-slide>.sp-media{height:100%}.sp-gallery-slide .sp-media img,.sp-gallery-slide .sp-media video{height:100%;max-height:none;object-fit:cover}.sp-gallery-controls{position:absolute;inset:0;pointer-events:none}.sp-gallery-controls[hidden],.sp-mosaic[hidden],.sp-album-viewer[hidden],.sp-gallery-dot[hidden]{display:none}.sp-gallery-controls button{position:absolute;top:50%;transform:translateY(-50%);display:grid;place-items:center;width:26px;height:26px;padding:5px;border:0;border-radius:50%;background:rgba(255,255,255,.9);color:#555;box-shadow:0 1px 4px #0003;cursor:pointer;pointer-events:auto}.sp-gallery-prev{left:10px}.sp-gallery-next{right:10px}.sp-gallery-prev svg{transform:rotate(180deg)}.sp-gallery-controls svg{width:100%;height:100%}.sp-gallery-controls button:disabled{visibility:hidden;pointer-events:none}.sp-gallery-dots{display:flex;justify-content:center;align-items:center;gap:4px;height:24px}.sp-gallery-dot{width:6px;height:6px;border-radius:50%;background:#a8a8a8;flex:none}.sp-gallery-dot.sp-active{background:#0095f6}
.sp-gallery--x{display:flex;flex-direction:column;border:0;border-radius:0}.sp-gallery--x .sp-gallery-dots{order:-1;justify-content:flex-start;height:16px}.sp-gallery--x .sp-gallery-dot{width:4px;height:4px;background:#71767b66}.sp-gallery--x .sp-gallery-dot.sp-active{background:#71767b}.sp-gallery--x .sp-gallery-track{gap:4px;padding-right:32%}.sp-gallery--x .sp-gallery-slide{flex-basis:100%;border-radius:8px;aspect-ratio:var(--sp-media-ratio,1)}
.sp-gallery--threads .sp-gallery-track{gap:6px;padding-right:15%}.sp-gallery--threads .sp-gallery-slide{flex-basis:100%;border-radius:12px}.sp-gallery--threads{border:0;border-radius:0}.sp-gallery--threads .sp-gallery-controls button{background:rgba(32,32,32,.65);color:#fff;width:28px;height:28px}
.sp-gallery--tiktok .sp-gallery-stage,.sp-gallery--tiktok .sp-gallery-track{height:100%}.sp-gallery--tiktok .sp-gallery-slide{height:100%;aspect-ratio:auto}.sp-gallery--tiktok .sp-media img{object-fit:contain;background:#000}.sp-gallery--tiktok .sp-gallery-dots{position:absolute;bottom:106px;left:12px;right:12px;pointer-events:none}.sp-gallery--tiktok .sp-gallery-dot{background:#ffffff66;width:5px;height:5px}.sp-gallery--tiktok .sp-gallery-dot.sp-active{background:#fff}.sp-gallery--tiktok .sp-counter{top:12px;right:12px;background:#0006}
.sp-gallery--pinterest .sp-gallery-dots{position:absolute;bottom:8px;left:0;right:0}.sp-gallery--pinterest .sp-gallery-dot{background:#ffffff80;box-shadow:0 0 2px #0007}.sp-gallery--pinterest .sp-gallery-dot.sp-active{background:#fff}.sp-gallery--pinterest .sp-gallery-controls button{width:32px;height:32px;color:#111}
.sp-gallery-track:focus-visible,.sp-gallery-controls button:focus-visible,.sp-mosaic-tile:focus-visible,.sp-album-back:focus-visible,.sp-viewport:focus-visible{outline:2px solid #3b82f6;outline-offset:-2px}
.sp-media-group{overflow:hidden}.sp-mosaic{display:grid;gap:2px;grid-template-columns:repeat(2,minmax(0,1fr));aspect-ratio:1.5}.sp-mosaic-tile{position:relative;display:block;min-width:0;min-height:0;border:0;padding:0;overflow:hidden;background:#171717;cursor:pointer}.sp-mosaic-tile>.sp-media{height:100%}.sp-mosaic-tile .sp-media img,.sp-mosaic-tile .sp-media video{height:100%;object-fit:cover}.sp-mosaic--3{grid-template-rows:repeat(2,minmax(0,1fr))}.sp-mosaic--3>:first-child{grid-row:span 2}.sp-mosaic--4{grid-template-rows:repeat(2,minmax(0,1fr))}.sp-mosaic--bluesky{gap:4px}.sp-mosaic--bluesky.sp-mosaic--2,.sp-mosaic--bluesky.sp-mosaic--3{aspect-ratio:2}.sp-mosaic--bluesky.sp-mosaic--4{aspect-ratio:1.5}
.sp-mosaic--facebook,.sp-mosaic--linkedin{aspect-ratio:1}.sp-mosaic--facebook.sp-mosaic--3,.sp-mosaic--linkedin.sp-mosaic--3{grid-template-columns:2fr 1fr}.sp-mosaic--facebook.sp-mosaic--4,.sp-mosaic--linkedin.sp-mosaic--4{grid-template-columns:2fr 1fr;grid-template-rows:repeat(3,minmax(0,1fr))}.sp-mosaic--facebook.sp-mosaic--4>:first-child,.sp-mosaic--linkedin.sp-mosaic--4>:first-child{grid-row:span 3}
.sp-mosaic--landscape.sp-mosaic--facebook.sp-mosaic--3,.sp-mosaic--landscape.sp-mosaic--linkedin.sp-mosaic--3{grid-template-columns:repeat(2,minmax(0,1fr));grid-template-rows:2fr 1fr}.sp-mosaic--landscape.sp-mosaic--facebook.sp-mosaic--3>:first-child,.sp-mosaic--landscape.sp-mosaic--linkedin.sp-mosaic--3>:first-child{grid-row:auto;grid-column:span 2}
.sp-mosaic--landscape.sp-mosaic--facebook.sp-mosaic--4,.sp-mosaic--landscape.sp-mosaic--linkedin.sp-mosaic--4{grid-template-columns:repeat(3,minmax(0,1fr));grid-template-rows:2fr 1fr}.sp-mosaic--landscape.sp-mosaic--facebook.sp-mosaic--4>:first-child,.sp-mosaic--landscape.sp-mosaic--linkedin.sp-mosaic--4>:first-child{grid-row:auto;grid-column:span 3}
.sp-mosaic--5{grid-template-columns:repeat(6,minmax(0,1fr));grid-template-rows:repeat(2,minmax(0,1fr))}.sp-mosaic--5>.sp-mosaic-tile{grid-column:span 2}.sp-mosaic--5>.sp-mosaic-tile:nth-child(-n+2){grid-column:span 3}
.sp-mosaic--linkedin.sp-mosaic--5{grid-template-columns:2fr 1fr;grid-template-rows:repeat(4,minmax(0,1fr));aspect-ratio:4/5}.sp-mosaic--linkedin.sp-mosaic--5>.sp-mosaic-tile{grid-column:auto}.sp-mosaic--linkedin.sp-mosaic--5>:first-child{grid-row:span 4}.sp-mosaic--landscape.sp-mosaic--linkedin.sp-mosaic--5{grid-template-columns:repeat(4,minmax(0,1fr));grid-template-rows:3fr 1fr;aspect-ratio:1}.sp-mosaic--landscape.sp-mosaic--linkedin.sp-mosaic--5>:first-child{grid-row:auto;grid-column:span 4}
.sp-mosaic--linkedin.sp-mosaic--2{aspect-ratio:calc(2 * var(--sp-first-ratio,1))}.sp-mosaic--linkedin.sp-mosaic--portrait:not(.sp-mosaic--2){aspect-ratio:max(.8,calc(1.5 * var(--sp-first-ratio,1)))}.sp-mosaic--linkedin.sp-mosaic--landscape.sp-mosaic--3{aspect-ratio:calc(var(--sp-first-ratio,1) / 1.5)}.sp-mosaic--linkedin.sp-mosaic--landscape.sp-mosaic--4{grid-template-rows:3fr 1fr;aspect-ratio:calc(var(--sp-first-ratio,1) / 1.333333)}.sp-mosaic--linkedin.sp-mosaic--landscape.sp-mosaic--5{grid-template-rows:4fr 1fr;aspect-ratio:calc(var(--sp-first-ratio,1) / 1.25)}

.sp-mosaic--telegram{aspect-ratio:1}.sp-mosaic--telegram.sp-mosaic--2{aspect-ratio:2}.sp-mosaic--telegram.sp-mosaic--landscape.sp-mosaic--2{grid-template-columns:1fr;grid-template-rows:1fr 1fr;aspect-ratio:1}.sp-mosaic--telegram.sp-mosaic--landscape.sp-mosaic--3{grid-template-rows:2fr 1fr}.sp-mosaic--telegram.sp-mosaic--landscape.sp-mosaic--3>:first-child{grid-row:auto;grid-column:span 2}.sp-mosaic--album{display:flex;flex-direction:column;aspect-ratio:auto}.sp-album-row{display:flex;gap:2px;min-height:0}.sp-more{position:absolute;inset:0;display:grid;place-items:center;background:#0008;color:#fff;font:32px Arial,sans-serif}.sp-album-viewer{background:#000;color:#fff}.sp-album-back{border:0;padding:10px 12px;background:none;color:inherit;font:12px Arial,sans-serif;cursor:pointer}.sp-gallery--viewer .sp-gallery-slide{aspect-ratio:1}.sp-gallery--viewer .sp-media img,.sp-gallery--viewer .sp-media video{object-fit:contain}.sp-gallery--viewer .sp-counter{font-size:12px}
@media(hover:none) and (pointer:coarse){.sp-gallery--instagram .sp-gallery-controls,.sp-gallery--threads .sp-gallery-controls,.sp-gallery--pinterest .sp-gallery-controls{display:none}}


/* Light themes mirror each platform's native light surface. Dark remains the default. */
.sp-theme-dark{color-scheme:dark}.sp-theme-light{color-scheme:light;background:#fff;color:#0f1419}
.sp-theme-light .sp-avatar{border-color:rgba(0,0,0,.12);background:#e5e7eb;color:#171717}.sp-theme-light .sp-muted{color:#536471}
.sp-theme-light .sp-media{background:#eff3f4}.sp-theme-light .sp-media--natural img,.sp-theme-light .sp-media--natural video{background:#f2f2f2}.sp-theme-light .sp-empty{background:linear-gradient(135deg,#f7f9f9,#eff3f4);color:#536471}
.sp-theme-light.sp-x{background:#fff;color:#0f1419}.sp-theme-light .sp-x-handle,.sp-theme-light .sp-x-time{color:#536471}.sp-theme-light .sp-x-media,.sp-theme-light .sp-x-thread{border-color:#eff3f4}
.sp-theme-light.sp-instagram{background:#fff;color:#262626}
.sp-theme-light.sp-facebook{background:#fff;color:#050505}.sp-theme-light .sp-facebook-meta{color:#65676b}
.sp-theme-light.sp-linkedin{background:#fff;color:#191919}.sp-theme-light .sp-linkedin-meta{color:#666}.sp-theme-light .sp-follow{color:#0a66c2}
.sp-theme-light.sp-tiktok .sp-media{background:#000}.sp-theme-light.sp-tiktok{background:#000;color:#fff;color-scheme:dark}.sp-theme-light .sp-tiktok-avatar{border-color:#fff;background:#525252;color:#fff}
.sp-theme-light.sp-youtube{background:#fff;color:#0f0f0f}.sp-theme-light .sp-youtube-meta{color:#606060}.sp-theme-light .sp-youtube-description{background:#f2f2f2;color:#0f0f0f}
.sp-theme-light.sp-telegram{background-color:#d8e8ef;background-image:radial-gradient(rgba(80,120,145,.18) 1px,transparent 1px);color:#17212b}.sp-theme-light .sp-bubble{background:#e1ffc7;box-shadow:0 1px 2px rgba(0,0,0,.16)}.sp-theme-light .sp-bubble-time{color:#5682a3}.sp-theme-light.sp-telegram .sp-muted{color:#5c6f78}
.sp-theme-light.sp-bluesky{background:#fff;color:#0f1419}.sp-theme-light .sp-bluesky-post+.sp-bluesky-post,.sp-theme-light .sp-bluesky-media{border-color:#e6e9ec}.sp-theme-light .sp-bluesky-handle,.sp-theme-light .sp-bluesky-time{color:#536471}
.sp-theme-light.sp-threads{background:#fff;color:#101010}.sp-theme-light .sp-thread-age{color:#737373}.sp-theme-light .sp-thread-line{background:#dbdbdb}.sp-theme-light .sp-thread-media{border-color:#dbdbdb}
.sp-theme-light.sp-pinterest{background:#fff;color:#111}.sp-theme-light .sp-pin-media{background:#efefef}.sp-theme-light .sp-pin-description{color:#5f5f5f}
.sp-theme-light.sp-forem{background:#fff;color:#171717}.sp-theme-light .sp-forem-meta{color:#717171}.sp-theme-light .sp-forem-copy{color:#3d3d3d}
.sp-theme-light.sp-unsupported{background:#fff;color:#536471}
`;
